repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-docstring-first
          - id: debug-statements
          - id: double-quote-string-fixer
          - id: requirements-txt-fixer
          - id: check-added-large-files
          - id: check-ast
          - id: check-builtin-literals
          - id: check-case-conflict
          - id: destroyed-symlinks
          - id: check-merge-conflict
          - id: check-yaml
          - id: debug-statements
          - id: detect-private-key
          - id: fix-byte-order-marker
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v1.5.4
      hooks:
          - id: autopep8
    - repo: https://github.com/asottile/add-trailing-comma
      rev: v2.0.1
      hooks:
          - id: add-trailing-comma
            args: [--py36-plus]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.7.4
      hooks:
          - id: pyupgrade
            args: [--py36-plus]
